frame_id: lidar
map_frame: map
odom_frame: odom
map_resolution: 0.10
map_size: 220
map_start_x: 0
map_start_y: 0
map_update_distance_thresh: 0.5
map_update_angle_thresh: 0.4
map_pub_period: 1
map_multi_res_levels: 3
update_factor_free: 0.7
update_factor_occupied: 0.4
laser_min_dist: 0.5
laser_max_dist: 20.0
laser_z_min_value: -1.0
laser_z_max_value: 1.0
pub_map_odom_transform: true
output_timing: false
scan_subscriber_queue_size: 5
pub_map_scanmatch_transform: false
tf_map_scanmatch_transform_frame_name: lidar